### ISSUE TITLE
When I compile the Binding project some methods are missing from the DLL

### ISSUE THREAD

**Issue by SeadnaS** [Laerdal/Xamarin.AzureCommunicationCalling#18]
Hi and thank you for this very useful repo.

Having some issues getting the bindings to work properly when compiling and using the DLLs in the TestApp solution. Any help is very much appreciated.

I can successfully compile the Bindings project however when I replace the Nuget packages in TestApp with references to the Bidnings DLLs I get some red lines in VS.

In CallingManager.cs:

> The type or namespace name 'Communication' does not exist in the namespace 'Com.Azure' (are you missing an assembly reference?)	

When I look in Bindings  I see that I need to change the using to Com.Azure.Android.Communication.Calling and this clears up some of the red lines. However, there are still some left.

It appears that CallClient class is missing the CreateCallAgent, DeviceManager methods, DeviceManager is missing the CameraList method, Call is missing the Hangup method and CallAgent is missing the Call Method. Also HangupOptions does not exist. See below.

> Error	'CallClient' does not contain a definition for 'CreateCallAgent' and no accessible extension method 'CreateCallAgent' accepting a first argument of type 'CallClient' could be found (are you missing a using directive or an assembly reference?)
> 
> Error	'CallClient' does not contain a definition for 'DeviceManager' and no accessible extension method 'DeviceManager' accepting a first argument of type 'CallClient' could be found (are you missing a using directive or an assembly reference?)
> 
> Error	'DeviceManager' does not contain a definition for 'CameraList' and no accessible extension method 'CameraList' accepting a first argument of type 'DeviceManager' could be found (are you missing a using directive or an assembly reference?)
> 
> Error	The type or namespace name 'HangupOptions' could not be found (are you missing a using directive or an assembly reference?)
> 
> Error	'Call' does not contain a definition for 'Hangup' and no accessible extension method 'Hangup' accepting a first argument of type 'Call' could be found (are you missing a using directive or an assembly reference?)
> 
> Error	'DeviceManager' does not contain a definition for 'CameraList' and no accessible extension method 'CameraList' accepting a first argument of type 'DeviceManager' could be found (are you missing a using directive or an assembly reference?)
> 
> Error	'CallAgent' does not contain a definition for 'Call' and no accessible extension method 'Call' accepting a first argument of type 'CallAgent' could be found (are you missing a using directive or an assembly reference?)

Any idea what I may be doing wrong?

**Comment by tompi** [comment]
Hey, just to clarify: why are you trying to compile the bindings yourself?

It should be sufficient to use the nugets available on nuget.org.

To compile the bindings solution you first need to run the "*.sh" scripts to download native libs from maven and cocoapod, but you really dont wanna do that unless you HAVE TO ;-)

**Comment by SeadnaS** [comment]
Hi Thomas,



We need to support a device running Android 5.1 and we were hoping to
compile the binding to target the correct API level.



*From:* Thomas Haukland ***@***.***>
*Sent:* Wednesday 19 May 2021 14:26
*To:* Laerdal/Xamarin.AzureCommunicationCalling <
***@***.***>
*Cc:* SeadnaS ***@***.***>; Author <
***@***.***>
*Subject:* Re: [Laerdal/Xamarin.AzureCommunicationCalling] When I compile
the Binding project some methods are missing from the DLL (#18)



Hey, just to clarify: why are you trying to compile the bindings yourself?

It should be sufficient to use the nugets available on nuget.org.

To compile the bindings solution you first need to run the "*.sh" scripts
to download native libs from maven and cocoapod, but you really dont wanna
do that unless you HAVE TO ;-)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/issues/18#issuecomment-844104533>,
or unsubscribe

**Comment by tompi** [comment]
@SeadnaS Ok, I see what you are trying to do now.  The ACS team used  "CompleteableFuture" in their lib and hence had a minimum android target of sdk 24...

In Beta-8, the switched to using retrofuture to be able to support devices as low as 21. Unfortunately, this lead to me bein unable to bind the lib, since the bindings generator doesnt like the retrofuture lib:

https://stackoverflow.com/questions/66366829/binding-method-returning-retrofuture-completablefuture

If you are able to bind the retrofuture library(either making a nuget or just a private repo), I will be able to bind latest versions!

Other option I was thinking about was making a wrapper library where I expose the retrofuture usages as regular completablefutures, and bind this wrapper, but this would still limit usage to sdk 24... So it wouldnt help you :( Also, I dont really have time to go down this route...

@mariusu-msft Perhaps you could dig up a bindings expert to help with this retrofuture issue? Im sure  @davidbritch or somebody else at MS familiar with bindings would know what to do(I hope ;-)

**Comment by tompi** [comment]
@SeadnaS Just to clarify your initial question, you get this error

"Error 'CallClient' does not contain a definition for 'CreateCallAgent' and no accessible extension method"

Since the the signature of the java method "CreateCallAgent" changed in beta-8 and forward from this:

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html

to this:

https://github.com/retrostreams/android-retrofuture/blob/master/src/main/java/java9/util/concurrent/CompletableFuture.java

And this last one fails to bind. If you check out the build-log from the binding you will notice it complains about this.

**Comment by tompi** [comment]
@SeadnaS I worked around this now by creating another helper library. 

You should be able to use latest version of ACS sdk on Android also now(2.0.0),
by utilizing the helper library(Just some static methods to replace those missing during binding)

See 37,38 and 96 of this file for examples:
https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/blob/master/TestApp/AzureCommunicationVideoTest.Android/ACS/CallingManager.cs
